# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rbozhko <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/12/30 13:42:51 by rbozhko           #+#    #+#              #
#    Updated: 2017/12/26 15:04:33 by rbozhko          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


NAME = libft.a

CC = gcc

SRC = ft_atoi.c ft_bzero.c ft_is_whitespace.c ft_isalnum.c ft_isalpha.c \
	  ft_isascii.c ft_isdigit.c ft_isprint.c ft_isspace.c ft_itoa.c \
	  ft_lstadd.c ft_lstdel.c ft_lstdelone.c ft_lstiter.c ft_lstmap.c \
	  ft_lstnew.c ft_memalloc.c ft_memccpy.c ft_memchr.c ft_memcmp.c \
	  ft_memcpy.c ft_memdel.c ft_memmove.c ft_memset.c ft_numlen.c \
	  ft_putchar.c ft_putchar_fd.c ft_putendl.c ft_putendl_fd.c \
	  ft_putnbr.c ft_putnbr_fd.c ft_putstr.c ft_putstr_fd.c \
	  ft_quick_power.c ft_strcat.c ft_strchr.c ft_strclr.c ft_strcmp.c \
	  ft_strcpy.c ft_strdel.c ft_strdup.c ft_strequ.c ft_striter.c \
	  ft_striteri.c ft_strjoin.c ft_strlcat.c ft_strlen.c ft_strmap.c \
	  ft_strmapi.c ft_strncat.c ft_strncmp.c ft_strncpy.c ft_strnequ.c \
	  ft_strnew.c ft_strnstr.c ft_strrchr.c ft_strsplit.c ft_strstr.c \
	  ft_strsub.c ft_strtrim.c ft_tolower.c ft_toupper.c ft_wordlen.c \
	  ft_words_count.c ft_is_numeric.c ft_putbidstr.c ft_bidlen.c \
	  ft_atoi_base.c ft_countdown.c ft_bid_findstr.c ft_create_bid_arr.c \
	  ft_count_char.c ft_free_bidarr.c ft_lstrip.c ft_rstrip.c ft_strip.c \
	  ft_read_file.c ft_skip_whitespaces.c ft_reverse_str.c ft_putnbrendl.c \
	  ft_putnbrendl_fd.c ft_is_int.c ft_throw_exception.c ft_print_iarr.c \
	  ft_bidarrjoin.c ft_omit_whitespaces.c ft_is_sorted.c get_next_line.c \
	  ft_find_biggest.c ft_find_smallest.c ft_abs.c

OBJ = $(SRC:.c=.o)

CFLAGS = -c -Wall -Wextra -Werror -O3

HEADER = libft.h

all: $(NAME)

$(NAME): $(OBJ)
	@ar rc $(NAME) $(OBJ)
	@echo "\033[0;36mLibft is compiled\033[0m"

%.o : %.c
	@$(CC) $(CFLAGS) $<

clean:
	@rm -rf $(OBJ)

fclean: clean
	@rm -rf $(NAME)

re: fclean all
